baseurl = "http://codeinthehole.com/"
title = "David Winterbottom"
languageCode = "en-us"

author = "David Winterbottom"
copyright = "David Winterbottom, All rights reserved."

[params]
  logo      = "/images/me-high-res.jpg"
  twitter   = "https://twitter.com/codeinthehole"
  github    = "https://github.com/codeinthehole/"
  email     = "david.winterbottom@gmail.com"
