baseurl = "http://codeinthehole.com/"
title = "David Winterbottom"
languageCode = "en-us"

PygmentsCodeFences = true

[params]
    author = "David Winterbottom"
    description = "A software engineer working in London."
